version: '3.9'

services:
  # Databases
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - platform

  # Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - platform

  # Message Queue
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - platform

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - platform

  # Tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"  # UI
    networks:
      - platform

  # Metrics
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./infra/services/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - platform

  # Services
  binance-connection:
    build:
      context: .
      dockerfile: ./infra/docker/Dockerfile.binance-connection
    environment:
      binance_SERVER_URL: wss://api.binance.com/v2
      binance_API_KEY: ${binance_API_KEY}
      DB_HOST: postgres
      KAFKA_BROKER_1: kafka:9092
      REDIS_HOST: redis
    ports:
      - "50051:50051"  # gRPC
      - "8051:8051"    # HTTP
      - "9051:9051"    # Metrics
    depends_on:
      - postgres
      - kafka
      - redis
      - jaeger
    networks:
      - platform

volumes:
  postgres_data:

networks:
  platform:
    driver: bridge