FROM golang:1.23-alpine AS builder
ARG CMD_PATH=./cmd/api

WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /app/service ${CMD_PATH}

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /app/service .
ENTRYPOINT ["./service"]
